// src/app/pages/bills/bills.component.ts
import { Component, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { BankingService } from '../../services/banking.service';
import { CurrencyNairaPipe } from '../../pipes/currency-naira.pipe';
import { LucideAngularModule } from 'lucide-angular';
import { DatePipe } from '@angular/common';

@Component({
  selector: 'app-bills',
  standalone: true,
  imports: [CommonModule, CurrencyNairaPipe, LucideAngularModule, DatePipe],
  template: `
    <div class="space-y-8">
      <div>
        <h1 class="text-4xl font-bold text-foreground">Bills</h1>
        <p class="text-muted-foreground mt-2">Track and manage your upcoming bills.</p>
      </div>

      <!-- Bills Overview -->
      <div class="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
        <div class="bg-card border border-border rounded-lg p-4">
          <p class="text-sm text-muted-foreground">Total Bills</p>
          <p class="text-2xl font-bold text-foreground">{{ (bills | slice:0:1).length }}</p>
        </div>
        <div class="bg-card border border-border rounded-lg p-4">
          <p class="text-sm text-muted-foreground">Pending</p>
          <p class="text-2xl font-bold text-destructive">{{ getPendingCount() }}</p>
        </div>
        <div class="bg-card border border-border rounded-lg p-4">
          <p class="text-sm text-muted-foreground">Paid</p>
          <p class="text-2xl font-bold text-accent">{{ getPaidCount() }}</p>
        </div>
        <div class="bg-card border border-border rounded-lg p-4">
          <p class="text-sm text-muted-foreground">Total Amount</p>
          <p class="text-2xl font-bold text-foreground">{{ getTotalAmount() | currencyNaira }}</p>
        </div>
      </div>

      <!-- Bills List -->
      <div class="bg-card border border-border rounded-lg overflow-hidden">
        <div class="p-6 border-b border-border">
          <h3 class="font-semibold text-foreground">Your Bills</h3>
        </div>

        <div class="divide-y divide-border">
          <div *ngFor="let bill of bills" class="p-6 flex justify-between items-center hover:bg-secondary/20 transition-colors">
            <div class="flex items-center gap-4 flex-1">
              <div [ngClass]="{
                'bg-destructive/10 text-destructive': !bill.isPaid,
                'bg-accent/10 text-accent': bill.isPaid
              }" class="p-3 rounded-lg">
                <i-lucide [name]="bill.isPaid ? 'check-circle' : 'alert-circle'" size="20"></i-lucide>
              </div>

              <div class="flex-1">
                <p class="font-semibold text-foreground">{{ bill.name }}</p>
                <div class="flex gap-4 mt-1">
                  <span class="text-sm text-muted-foreground">{{ bill.category }}</span>
                  <span class="text-sm text-muted-foreground">Due: {{ bill.dueDate | date:'short' }}</span>
                </div>
              </div>
            </div>

            <div class="text-right mr-4">
              <p class="font-semibold text-foreground">{{ bill.amount | currencyNaira }}</p>
              <span [ngClass]="{
                'text-destructive': !bill.isPaid,
                'text-accent': bill.isPaid
              }" class="text-sm font-medium">
                {{ bill.isPaid ? 'Paid' : 'Pending' }}
              </span>
            </div>

            <button *ngIf="!bill.isPaid" (click)="payBill(bill.id)" class="bg-primary text-primary-foreground px-6 py-2 rounded-lg hover:bg-primary/90 transition-colors">
              Pay Now
            </button>
            <span *ngIf="bill.isPaid" class="text-accent font-semibold">✓ Paid</span>
          </div>
        </div>
      </div>
    </div>
  `,
  styles: []
})
export class BillsComponent implements OnInit {
  bills: any[] = [];

  constructor(private bankingService: BankingService) {}

  ngOnInit() {
    this.bankingService.bills$.subscribe(bills => {
      this.bills = bills;
    });
  }

  getPendingCount(): number {
    return this.bills.filter(b => !b.isPaid).length;
  }

  getPaidCount(): number {
    return this.bills.filter(b => b.isPaid).length;
  }

  getTotalAmount(): number {
    return this.bills.reduce((sum, b) => sum + b.amount, 0);
  }

  payBill(billId: string) {
    this.bankingService.payBill(billId);
  }
}

// app/bills/page.tsx
'use client'

import { mockBills } from '@/lib/mock-data'
import { Card } from '@/components/ui/card'
import { Button } from '@/components/ui/button'
import { Plus, CheckCircle2, AlertCircle } from 'lucide-react'

const categories = {
  utility: '⚡',
  insurance: '🛡️',
  subscription: '🔔',
}

export default function BillsPage() {
  const pendingBills = mockBills.filter(b => b.status === 'pending')
  const paidBills = mockBills.filter(b => b.status === 'paid')

  const totalPending = pendingBills.reduce((sum, bill) => sum + bill.amount, 0)

  return (
    <div className="space-y-8">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Bills</h1>
          <p className="text-muted-foreground mt-2">Track and pay your bills on time</p>
        </div>
        <Button>
          <Plus className="h-4 w-4" />
          Add Bill
        </Button>
      </div>

      {/* Summary Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <Card className="p-6">
          <p className="text-sm text-muted-foreground mb-2">Total Bills</p>
          <p className="text-2xl font-bold">{mockBills.length}</p>
        </Card>
        <Card className="p-6">
          <p className="text-sm text-muted-foreground mb-2">Pending Amount</p>
          <p className="text-2xl font-bold text-destructive">${totalPending.toFixed(2)}</p>
        </Card>
        <Card className="p-6">
          <p className="text-sm text-muted-foreground mb-2">Payment Success Rate</p>
          <p className="text-2xl font-bold text-green-600">100%</p>
        </Card>
      </div>

      {/* Upcoming Bills */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Upcoming Bills</h2>
        <div className="space-y-3">
          {pendingBills.map((bill) => {
            const dueDate = new Date(bill.due_date)
            const today = new Date()
            const daysUntilDue = Math.ceil((dueDate.getTime() - today.getTime()) / (1000 * 60 * 60 * 24))
            const isOverdue = daysUntilDue < 0
            const isDueSoon = daysUntilDue <= 3 && daysUntilDue >= 0

            return (
              <Card key={bill.id} className="p-4 flex items-center justify-between">
                <div className="flex items-center gap-4">
                  <div className="text-2xl">
                    {categories[bill.category as keyof typeof categories] || '📄'}
                  </div>
                  <div className="flex-1">
                    <p className="font-semibold">{bill.biller_name}</p>
                    <p className="text-sm text-muted-foreground">
                      Due {dueDate.toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}
                    </p>
                  </div>
                </div>

                <div className="flex items-center gap-4">
                  <div className="text-right">
                    <p className="font-semibold">${bill.amount.toFixed(2)}</p>
                    <p className={`text-xs font-medium ${
                      isOverdue ? 'text-destructive' : isDueSoon ? 'text-chart-3' : 'text-muted-foreground'
                    }`}>
                      {isOverdue ? '🔴 Overdue' : isDueSoon ? '🟡 Due soon' : `In ${daysUntilDue} days`}
                    </p>
                  </div>
                  <Button size="sm" variant={isDueSoon || isOverdue ? 'default' : 'outline'}>
                    Pay Now
                  </Button>
                </div>
              </Card>
            )
          })}
        </div>
      </div>

      {/* Paid Bills */}
      <div className="space-y-4">
        <h2 className="text-lg font-semibold">Recently Paid</h2>
        <div className="space-y-3">
          {paidBills.map((bill) => (
            <Card key={bill.id} className="p-4 flex items-center justify-between opacity-75">
              <div className="flex items-center gap-4">
                <CheckCircle2 className="h-5 w-5 text-green-600" />
                <div>
                  <p className="font-semibold">{bill.biller_name}</p>
                  <p className="text-sm text-muted-foreground">Paid on {new Date(bill.due_date).toLocaleDateString()}</p>
                </div>
              </div>
              <p className="font-semibold">${bill.amount.toFixed(2)}</p>
            </Card>
          ))}
        </div>
      </div>
    </div>
  )
}
